version: "2"

run:
  timeout: 5m
  go: '1.24'
  allow-parallel-runners: true

linters:
  default: standard

exclusions:
  rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        