project_name: testrigor-ci

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

archives:
  - formats: [ 'tar.gz' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
    - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:{{ .Version }}"
    - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/{{.ProjectName}}:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
    - --label=org.opencontainers.image.created={{.Date}}
    - --label=org.opencontainers.image.title={{.ProjectName}}
    - --label=org.opencontainers.image.revision={{.FullCommit}}
    - --label=org.opencontainers.image.version={{.Version}}

snapshot:
  version_template: "{{ .Tag }}-next"

sboms:
  - id: spdx-format
    artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_sbom.spdx.json"
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]
  - id: cyclonedx-format
    artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_sbom.cyclonedx.json"
    cmd: syft
    args: ["$artifact", "--output", "cyclonedx-json=$document"]